// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trswojxkjrlhkpktavmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyc3dvanhranJsaGtwa3Rhdm1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNjI1MDUsImV4cCI6MjA1NTYzODUwNX0.4m4cyRKCh_kCxwRAHcUvCfsWoBzmc4GiqIJ6knkgh7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);